name: Bug Report
description: Report an issue with MegaMek
title: "[ISSUE]: [Version Number] - Brief Description"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Prerequisites

        Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites Checklist
      description: Check the boxes to confirm you have met the prerequisites.
      options:
        - label: "I've tested the issue against the latest MILESTONE"
          required: true
        - label: "I've checked the BattleTech rules and information in the documents folder and found no answer"
          required: true
        - label: "I've checked to make sure that this issue has not already been filed"
          required: true
        - label: "I'm reporting the issue to the correct repository"
          required: true

  - type: markdown
    attributes:
      value: |
        ## Before Creating an Issue
        1. **Choose the Right Issue Tracker**: Use the GitHub Issue tracker for the appropriate program (MegaMek, MegaMekLab, MekHQ). If unsure, team members can redirect your report.
           - [MegaMek Issues](https://github.com/MegaMek/megamek/issues)
           - [MegaMekLab Issues](https://github.com/MegaMek/megameklab/issues)
           - [MekHQ Issues](https://github.com/MegaMek/mekhq/issues)

        2. **Check for Duplicates**: Avoid creating a new issue if one already exists.

        3. **Clarify Confusions Elsewhere**: If your issue stems from misunderstanding functionality, consult the forums rather than the issue tracker.

        4. **One Issue Per Ticket**: This ensures clarity and focus, allowing for individual tracking and resolution.

  - type: dropdown
    id: megamek-version
    attributes:
      label: MegaMek Version
      description: Select the MegaMek version you are using.
      options:
        - v0.50.0
        - v0.49.20
        - v0.49.19
        - v0.49.18
        - v0.49.17
        - v0.49.16
        - v0.49.15
        - v0.49.14
        - v0.49.13
        - v0.49.12
        - v0.49.11
        - v0.49.10
        - v0.49.9
        - v0.49.8
        - v0.49.7
      validations:
        required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: Enter the operating system and version you are using (e.g., Windows 11, macOS Ventura 13.0, Ubuntu 22.04 LTS). **REQUIRED**
    validations:
      required: true

  - type: dropdown
    id: java-version
    attributes:
      label: Java Version
      description: Select the Java version you are using. If unsure, check the version at the top of the megamek.log file. **REQUIRED**
      options:
        - Java 17
        - Java 11
        - Java 8
        - Java 21
        - Java 20
        - Java 19
        - Java 18
        - Java 16
        - Java 15
        - Java 14
        - Java 13
        - Java 12
        - Java 10
        - Java 9
        - Java 7
        - Java 6
        - Java 5
      validations:
        required: true

  - type: input
    id: player-name
    attributes:
      label: Player Name
      description: Your player name so developers can load the saved game. **REQUIRED**
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Expected Behavior

        Please describe the behavior you are expecting. **REQUIRED**

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What behavior did you expect to see?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Current Behavior

        What is the current behavior? **REQUIRED**

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe the current behavior you are experiencing.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Failure Information (for bugs)

        Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

        ### Steps to Reproduce

        Please provide detailed steps for reproducing the issue. **REQUIRED**

        1. step 1
        2. step 2
        3. you get it...

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe the steps necessary to reproduce this issue.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Context

        Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. **REQUIRED**

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide details about your setup (e.g., Firmware Version, SDK version, Toolchain version, any other specific configurations).
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Failure Logs

        Please include any relevant log snippets or files here. **Do not paste the entire log text directly into this ticket.** Attach log files instead. **REQUIRED**

  - type: textarea
    id: failure-logs
    attributes:
      label: Failure Logs
      description: Include relevant parts of the log files, or attach the log files to this issue.
      render: "none"
      placeholder: "Attach your log file after creating the issue."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Examples of Well-Reported Issues

        For an example of a comprehensive issue report, see [MekHQ #3195](https://github.com/MegaMek/mekhq/issues/3195). Accuracy and detail are crucial for quick and effective resolution.
