name: Bug Report
description: Report an issue with MegaMek
title: "[ISSUE]: [Version Number] - Brief Description"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Brief Description

        Please tell us, in one or two sentences, what happened and what it prevented you from doing.

  - type: textarea
    id: brief-description
    attributes:
      label: Brief Description
      description: Provide a short summary of what the issue is and how it impacts usage.

  - type: markdown
    attributes:
      value: |
        ## Prioritisation

        Please tick the appropriate tickboxes that apply to your bug.

  - type: checkboxes
    id: prioritisation
    attributes:
      label: Prioritisation Checklist
      description: Choose the severity of the bug.
      options:
        - label: "Hard Blocker - Prevents further use of the program (MegaMek, MekHQ, etc.)"
          required: false
        - label: "Soft Blocker - Prevents further use of the program, but I found a workaround"
          required: false
        - label: "Nuisance - Causes unexpected behavior but the program can still be used"
          required: false

  - type: markdown
    attributes:
      value: |
        ## User Environment

        Please provide details about your system and software versions.

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: Select your operating system.
      options:
        - Windows 10
        - Windows 11
        - Older Windows
        - Mac
        - Linux

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: Write which version of Java is installed on your machine. This can be found at the top of your megamek.log file in the megamek/logs folder.

  - type: dropdown
    id: megamek-version
    attributes:
      label: MegaMek Suite Version
      description: Select which version of MegaMek Suite you are using.
      options:
        - v0.50.0
        - v0.49.19.1
        - v0.49.19
        - Free Text (type manually)

  - type: markdown
    attributes:
      value: |
        ## Steps to Reproduce

        Please provide detailed steps of what you were doing when the bug occurred.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a detailed numbered list of steps.
      placeholder: "1. Step one\n2. Step two\n3. Step three"

  - type: markdown
    attributes:
      value: |
        ## Log Extract

        If you can see a Null Pointer Exception (NPE) in your log file, please paste that part here.

  - type: textarea
    id: log-extract
    attributes:
      label: Log Extract
      description: Provide a section of your log file, particularly Null Pointer Exceptions (NPE).

  - type: markdown
    attributes:
      value: |
        ## Files

        Please attach any relevant files, including saved games, zipped Customs folder, and log files.

  - type: textarea
    id: attached-files
    attributes:
      label: Attach Files
      description: Provide any relevant files by attaching them to the issue.
