name: Bug Report
description: Report an issue with MegaMek
title: "Brief Description"
labels: [bug]
body:
  - type: checkboxes
    id: hidden-prerequisites
    attributes:
      label: Required Checks
      description: These checks are required but won't be visible in the final report
      options:
        - label: "Repository check completed"
          required: true
        - label: "Latest MILESTONE version tested"
          required: true
        - label: "Discord consultation completed"
          required: true
        - label: "Documentation reviewed"
          required: true
        - label: "Issue tracker searched"
          required: true

  - type: textarea
    id: brief-description
    attributes:
      label: Brief Description *
      description: |
        Please describe the issue in detail:
        1. Provide in-game screenshots if possible.
        2. If it's a rules-related issue:
           - Specify the rulebook edition
           - Include the page number
           - Quote the relevant text
        3. If applicable, list the steps to reproduce the issue in the saved game.
      placeholder: "Describe the issue here..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity *
      description: Choose the severity of the bug.
      options:
        - "Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable."
        - "High (Major Disruption): A major feature is broken or incorrect, but a workaround exists."
        - "Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience."
        - "Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a detailed numbered list of steps.
      placeholder: "1. Step one\n2. Step two\n3. Step three"

  - type: input
    id: operating-system
    attributes:
      label: Operating System *
      description: Select your operating system
      placeholder: e.g. "Windows 11, Windows 10,Older Windows,Mac (be specific),Linux (be specific)"
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version *
      description: Enter the Java version from your MegaMek.log file
      placeholder: "Example: Java Vendor: Eclipse Adoptium     Java Version: 17.0.11"
    validations:
      required: true

  - type: input
    id: megamek-version
    attributes:
      label: MegaMek Suite Version *
      description: Enter your MegaMek version here
      placeholder: "Example: 0.50.02"
    validations:
      required: true

  - type: textarea
    id: attached-files
    attributes:
      label: Attach Files
      description: Provide any relevant files by attaching them to the issue.
      placeholder: "Drag and drop or click to upload relevant files."

  - type: checkboxes
    id: final-checks
    attributes:
      label: Final Checklist
      description: Before submitting, confirm the following
      options:
        - label: "I've verified this is a single, unique issue"
          required: true
        - label: "I've included all necessary information"
          required: true
