name: Bug Report
description: Report an issue with MegaMek
title: "[ISSUE]: [Version Number] - Brief Description"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Prerequisites

        Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

  - type: checkboxes
    id: prerequisites-and-pre-issue-checks
    attributes:
      label: Prerequisites and Pre-Issue Checklist
      description: Please confirm you have completed the following steps before submitting an issue.
      options:
        - label: "I've checked the BattleTech rules and information in the documents folder and found no answer to my issue"
          required: true
        - label: "I've tested the issue against the latest MILESTONE version"
          required: true
        - label: "I've checked to make sure that this issue has not already been filed"
          required: true
        - label: "I understand that if my issue stems from misunderstanding functionality, I should consult the forums rather than the issue tracker"
          required: true
        - label: "I'm reporting only one issue in this ticket for clarity and focus"
          required: true
        - label: "I'm reporting the issue to the correct repository: [MegaMek](https://github.com/MegaMek/megamek/issues), [MegaMekLab](https://github.com/MegaMek/megameklab/issues), or [MekHQ](https://github.com/MegaMek/mekhq/issues)"
          required: true

  - type: markdown
    attributes:
      value: |
        If you're unsure about which repository to report your issue to, team members can redirect your report if necessary.

  - type: markdown
    attributes:
      value: |
        ## Issue Description
        Please provide detailed information about the bug you've encountered. All fields are required.

  - type: textarea
    id: issue-summary
    attributes:
      label: Issue Summary
      description: Provide a brief (1-2 sentences) summary of the issue.
      placeholder: "Briefly describe the issue you're experiencing"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe the behavior you are currently experiencing.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe the behavior you expected to see.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps for reproducing the issue.
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
        ...
    validations:
      required: true

  - type: input
    id: megamek-version
    attributes:
      label: MegaMek Version
      description: Enter the MegaMek version you are using (e.g., v0.50.0).
      placeholder: "v0.50.0"
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: Enter the operating system and version you are using (e.g., Windows 11, macOS Ventura 13.0, Ubuntu 22.04 LTS).
    validations:
      required: true

  - type: dropdown
    id: java-version
    attributes:
      label: Java Version
      description: Select the Java version you are using. If unsure, check the version at the top of the megamek.log file.
      options:
        - Java 17 (Recommended)
        - Java 11
        - Java 8
        - Other (specify in context)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Provide any additional relevant information about your setup or conditions under which the issue occurs.
      placeholder: |
        - Specific game mode or scenario:
        - Any mods or custom content:
        - Any other relevant details:
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Failure Logs
        Please include any relevant log snippets here. For full logs, please compress them and attach them to this issue after submitting.

  - type: textarea
    id: failure-logs
    attributes:
      label: Failure Logs
      description: Include relevant parts of the log files here. For full logs, please attach them to the issue after submission.
      placeholder: "Paste relevant log snippets here. Attach full logs to the issue after submitting."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Thank you for providing this information. It will help us investigate and resolve the issue more effectively.

        ### Examples of Well-Reported Issues
        For an example of a comprehensive issue report, see [MekHQ #3195](https://github.com/MegaMek/mekhq/issues/3195). Accuracy and detail are crucial for quick and effective resolution.
