name: Bug Report
description: "Please review this before submitting a [bug report](https://github.com/MegaMek/megamek/wiki/Creating-an-Issue-(Bug-Report%2C-Request-for-Enhancement%2C-Errata))."

title: "Brief Description"
labels: [bug]
body:
  - type: textarea
    id: brief-description
    attributes:
      label: Brief Description *
      description: |
        Please describe the issue in detail:
        1. Provide in-game screenshots if possible.
        2. If it's a rules-related issue:
           - Specify the rulebook edition
           - Include the page number
           - Quote the relevant text
        3. If applicable, list the steps to reproduce the issue in the saved game.
      placeholder: "Describe the issue here..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a detailed numbered list of steps.
      placeholder: "1. Step one\n2. Step two\n3. Step three"

  - type: textarea
    id: attached-files
    attributes:
      label: Attach Files
      description: Please provide your logs folder (zipped) and any other relevant files.
      placeholder: "Drag and drop or click to upload relevant files."

  - type: dropdown
    id: severity
    attributes:
      label: Severity *
      description: Choose the severity of the bug.
      options:
        - "Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable."
        - "High (Major Disruption): A major feature is broken or incorrect, but a workaround exists."
        - "Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience."
        - "Low (Minor/Nuisance): Minor glitches or cosmetic issues that don't affect gameplay and occur rarely."
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## User Environment
        For the next sections go to the logs folder inside MegaMek (usually called 'logs'). Find the MegaMek.log file, open it with a text editor.

  - type: input
    id: custom-megamek-version
    attributes:
      label: MegaMek Suite Version *
      description: Enter your MegaMek version here
      placeholder: "Example: 0.50.02"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System *
      description: Select your operating system
      options:
        - "Windows 11"
        - "Windows 10"
        - "Windows 8/8.1"
        - "Windows 7"
        - "macOS"
        - "Linux"
        - "Other (Please specify in description)"
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version *
      description: Enter the Java version from your MegaMek.log file
      placeholder: "Example: Java Vendor: Eclipse Adoptium     Java Version: 17.0.11"
    validations:
      required: true

  - type: checkboxes
    id: final-checks
    attributes:
      label: Final Verification
      description: Please confirm the following before submitting
      options:
        - label: "I confirm this is a single, unique issue that hasn't been reported before"
          required: true
        - label: "I have included all necessary information and files to help reproduce this issue"
          required: true
        - label: "I have asked on MegaMek Discord about this issue"
          required: true
        - label: "I have confirmed this issue is being opened on the correct repository: MegaMek, MegaMekLab, or MekHQ"
          required: true
