name: Bug Report
description: Report an issue with MegaMek
title: "Brief Description"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        **Fields marked with a red asterisk (*) are mandatory to complete.**
        Please ensure you've completed these fields before submitting.

  - type: checkboxes
    id: prerequisites-and-pre-issue-checks
    attributes:
      label: Prerequisites and Pre-Issue Checklist
      description: Please confirm you have completed the following steps before submitting an issue.
      options:
        - label: "I've tested the issue against the latest MILESTONE version"
          required: true
        - label: "I've searched the Github tracker and haven't found the issue listed"
          required: true

  - type: markdown
    attributes:
      value: |
        ![How to Search the GitHub Tracker](https://i.imgur.com/QMJY7pll.png)

  - type: checkboxes
    id: prerequisites-and-pre-issue-checks-cont
    attributes:
      label: Additional Prerequisites
      options:
        - label: "I've asked on the MegaMek Discord about the error"
          required: true
        - label: "I've reviewed the BattleTech rules and MegaMek documentation, and I've confirmed that something isn't working as intended."
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity *
      description: Choose the severity of the bug.
      options:
        - "Critical - I can't use the program anymore or it crashes every time"
        - "High - I found a way to continue using the program, but it's still a problem"
   
