name: Bug Report
description: Report an issue with MegaMek
title: "Brief Description"
labels: [bug]
body:
  - type: checkboxes
    id: prerequisites-and-pre-issue-checks
    attributes:
      label: Prerequisites and Pre-Issue Checklist
      description: Please confirm you have completed the following steps before submitting an issue.
      options:
        - label: "I've tested the issue against the latest MILESTONE version"
          required: true
        - label: "I've checked the BattleTech rules and the information in the documents folder and found no answer to my issue"
          required: true
        - label: "I understand that if my issue stems from misunderstanding functionality, I should consult the forums rather than the issue tracker"
          required: true

  - type: markdown
    attributes:
      value: |
        ## Brief Description

        What happened? Please explain the issue in one or two sentences and how it stopped you from using the program. You can also upload a picture of the issue if possible.

  - type: textarea
    id: brief-description
    attributes:
      label: Brief Description
      description: Provide a short summary of what the issue is and how it impacts usage.

  - type: markdown
    attributes:
      value: |
        ## Severity

        How severe is the problem? Please select the option that best describes your situation.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Choose the severity of the bug.
      options:
        - Critical - I can't use the program anymore [Blocker]
        - High - I found a way to continue using the program, but it's still a problem [User Workaround Used]
        - Medium - The program still works, but it does something unexpected [Annoyance]
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## User Environment

        Go to the folder where your logs are saved (usually called `logs`). Find the `MegaMek.log` file, open it, and copy the text from the top part of the file. You can also upload a picture of the top part here. Here's an example of what it looks like:

        ![Example Screenshot](https://i.imgur.com/KD8cnvf.png)

  - type: dropdown
    id: operating-system
    attributes:
      label: Operating System
      description: What kind of computer are you using? Select your operating system (like Windows or Mac).
      options:
        - Windows 11
        - Windows 10
        - Older Windows
        - Mac
        - Linux

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: What version of Java is on your computer? You can find this information at the top of your `MegaMek.log` file.

  - type: dropdown
    id: megamek-version
    attributes:
      label: MegaMek Suite Version
      description: Which version of MegaMek are you using? Pick your version from the list. If you select "Free Text," please enter your version in the box below.
      options:
        - v0.50.0
        - v0.49.19.1
        - v0.49.19
        - v0.49.18
        - v0.49.17
        - v0.49.16
        - v0.49.15
        - Free Text (type manually)

  - type: input
    id: custom-megamek-version
    attributes:
      label: Custom MegaMek Version
      description: If you selected "Free Text" in the version dropdown, enter your MegaMek version here.
      placeholder: "Enter your MegaMek version here if it's not listed above."

  - type: markdown
    attributes:
      value: |
        ## Steps to Reproduce

        How did the problem happen? Please list the steps you followed before the issue appeared.

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a detailed numbered list of steps.
      placeholder: "1. Step one\n2. Step two\n3. Step three"

  - type: markdown
    attributes:
      value: |
        ## Files

        Please zip (compress) your logs folder and upload the file here. If you're not sure how to zip the folder, ask for help.

  - type: textarea
    id: attached-files
    attributes:
      label: Attach Files
      description: Provide any relevant files by attaching them to the issue.

  - type: checkboxes
    id: final-checks
    attributes:
      label: Final Checklist
      description: Before submitting, confirm the following steps
      options:
        - label: "I've checked to make sure that this issue has not already been filed"
          required: true
        - label: "I'm reporting only one issue in this ticket for clarity and focus"
          required: true
        - label: "I'm reporting the issue to the correct repository: MegaMek (https://github.com/MegaMek/megamek/issues), MegaMekLab (https://github.com/MegaMek/megameklab/issues), or MekHQ (https://github.com/MegaMek/mekhq/issues)"
          required: true
