blank_issues_enabled: true

contact_links:
  - name: Questions
    url: https://discord.gg/megamek
    about: You can join the discussions on Discord.

  - name: MegaMek Wiki
    url: https://github.com/MegaMek/megamek/wiki
    about: Before opening a new issue, please check the MegaMek Wiki for information.

  - name: BattleTech Forums
    url: https://bg.battletech.com/forums/index.php?board=29.0
    about: Join the discussions and find more information on the official BattleTech Forums.
