name: Request for Enhancement
description: >
  Use this to request an enhancement or new feature for MegaMek. Before submitting an RFE please review the following
  [Content Policy](https://github.com/MegaMek/megamek/wiki/Unofficial-or-Non%E2%80%90Canon-Content-Policy)
title: "Brief Description"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        **Fields marked with a red asterisk (*) are mandatory to complete.**
        In this form, you'll provide a description of the issue, steps to reproduce it, your system details, and any files that may help us resolve the problem.

  - type: checkboxes
    id: prerequisites-and-pre-issue-checks
    attributes:
      label: Prerequisites and Pre-Issue Checklist
      description: Please confirm you have completed the following steps before submitting an issue.
      options:
        - label: >
            I'm reporting the issue to the correct repository:
            - [MegaMek](https://github.com/MegaMek/megamek/issues)
            - [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
            - [MekHQ](https://github.com/MegaMek/mekhq/issues)
          required: true
        - label: "Does this conform with our Content Policy linked above?"
          required: true
        - label: "I've searched the GitHub tracker and haven't found the issue listed"
          required: true

  - type: markdown
    attributes:
      value: "![How to Search the GitHub Tracker](https://i.imgur.com/QMJY7pll.png)"

  - type: dropdown
    id: rfe
    attributes:
      label: RFE Details *
      description: Please select one of the following options.
      options:
        - "This is an all new feature"
        - "This is an improvement to an existing feature"
        - "This is an implementation of a missing official rule"
        - "This is a request to implement Errata"
    validations:
      required: true

  - type: textarea
    id: brief-description
    attributes:
      label: Brief Description *
      description: |
        ## Brief Description of feature *
      placeholder: >
        Please describe the enhancement in detail and include screenshots and mockups if possible. If this is an improvement
        to an existing feature, outline what is changing and what would need to change. For implementation of missing rules
        or equipment from the official core rules, please include the book, page number, and edition. If this is about
        implementing errata, please reference the specific errata from the official errata documents found
        [here](https://bg.battletech.com/errata/).
    validations:
      required: true

  - type: dropdown
    id: megamek-version
    attributes:
      label: MegaMek Suite Version *
      description: >
        Which version of MegaMek are you using? Pick your version from the list. If you select "Free Text," please enter
        your version in the box below. All RFEs must be checked against the most current development release.
      options:
        - "v0.50.0"
        - "v0.49.19.1"
        - "v0.49.19"
        - "v0.49.18"
        - "v0.49.17"
        - "v0.49.16"
        - "v0.49.15"
        - "Free Text (type manually)"
    validations:
      required: true

  - type: input
    id: custom-megamek-version
    attributes:
      label: Custom MegaMek Version
      description: If you selected "Free Text" in the version dropdown, enter your MegaMek version here.
      placeholder: "Enter your MegaMek version here if it's not listed above."

  - type: textarea
    id: attached-files
    attributes:
      label: Attach Files
      description: Provide any relevant files by attaching them to the issue.
      placeholder: "Drag and drop or click to upload relevant files."

  - type: checkboxes
    id: final-checks
    attributes:
      label: Final Checklist
      description: Before submitting, confirm the following steps:
      options:
        - label: "I've checked to make sure that this RFE has not already been filed"
          required: true
        - label: "I am reporting only one issue in this ticket for clarity and focus"
          required: true

  - type: markdown
    attributes:
      value: |
        **You will not be able to submit this report unless all fields marked with a red asterisk (*) are complete and filled out before submitting your report.**
