name: Auto-label issues based on severity

on:
  issues:
    types: [opened, edited]

jobs:
  label-issues:
    runs-on: ubuntu-latest
    steps:
    - name: Log issue body and severity
      uses: actions/github-script@v6
      with:
        script: |
          // Log the full issue body
          const issueBody = context.payload.issue.body;
          console.log('Issue Body:', issueBody);

          // Regular expression to extract severity from the issue body
          const severityRegex = /### Severity \*\n\n(.*)/g;
          const severityMatch = severityRegex.exec(issueBody);
          
          // Log the match result of the regex
          console.log('Severity Match:', severityMatch);

          const labels = [];
          if (severityMatch) {
            const severity = severityMatch[1].toLowerCase().trim();
            
            // Log the detected severity
            console.log('Detected Severity:', severity);

            // Assign labels based on detected severity
            if (severity.includes("critical")) {
              labels.push('Severity: Critical', 'blocker');
            } else if (severity.includes("high")) {
              labels.push('Severity: High');
            } else if (severity.includes("medium")) {
              labels.push('Severity: Medium');
            } else if (severity.includes("low")) {
              labels.push('Severity: Low');
            }
          } else {
            console.log('No severity match found.');
          }

          // Make sure owner, repo, and issue number are defined before adding labels
          const { owner, repo } = context.repo;
          const issue_number = context.payload.issue.number;
          
          if (labels.length > 0 && owner && repo && issue_number) {
            console.log(`Applying labels: ${labels} to issue #${issue_number} in ${owner}/${repo}`);
            await github.issues.addLabels({
              owner: owner,
              repo: repo,
              issue_number: issue_number,
              labels: labels
            });
            console.log('Labels applied:', labels);
          } else {
            console.log('No labels applied or missing context.');
          }
